### ISSUE TITLE
cargo build error

### ISSUE THREAD

**Issue by Patt1607** [packom/mbus-httpd#8]
Hello,

I'll get an error when i execute following:

```
cd ~
git clone https://github.com/packom/mbus-httpd
cd mbus-httpd
cargo build
```

after cargo build i get:

```
sudo cargo build
    Updating crates.io index
Segmentation fault
```

Anyone can help?

**Comment by packom** [comment]
That's odd.  It works fine for me.  Are you actually running
```
sudo cargo build
```
You should probably instead be running
```
cargo build
```

**Comment by Patt1607** [comment]
I've tried both, 

`Cargo build`
and
`sudo Cargo Build`

Both ends with the same error

**Comment by packom** [comment]
It sounds more like a rust install issue than a problem with mbus-httpd.  Can you try creating, building and running a rust hello world project as explained here: https://doc.rust-lang.org/cargo/getting-started/first-steps.html

If you hit problems with that, the problem is with your rust install.

If that works fine, let me have some more details about your environment - host type you are compiling on, rust version.

**Comment by Patt1607** [comment]
hello-world runs with rust without error

Raspberry pi 3B+

Rust is installed from: 
docker run --rm -ti -v some_local_dir:/home/build/builds piersfinlayson/build

Container version 0.3.6
OpenSSL version 1.1.1g
rustc 1.44.1 (c7087fe00 2020-06-17)
MUSL version 1.1.24
MUSL GCC version 9.2.0
Architecture: armv6l
Current version of OpenSSL is 1.1.1g

**Comment by packom** [comment]
This looks like an issue with the build container piersfinlayson/build.  I'll rebuild an up to date copy for armv7l and test that.

**Comment by piersfinlayson** [comment]
Try using container piersfinlayson/build-armv7l:0.3.6

This built successfully on my Pi 3B+.
